== About

you are reading the cache2k user guide which walks through all major
feature in a separate section to give an overview of the functionality.

[CAUTION]
===============================
You are reading a documentation for an unstable development version. The docuemntation is currently work in process
and may get additional updates. Some parts of the documentation may refer to features in an unreleased or upcoming
cache2k version.
===============================

The following documentation resources are available:

- link:user-guide.html[User Guide (this document) - HTML Version ]
- link:user-guide.pdf[User Guide (this document) - PDF Version]
- link:apidocs/cache2k-api/index.html[API Java Doc]

The documentation of the stable 1.0 version of cache2k is available at:

- https://cache2k.org/docs/1.0/user-guide.html[User Guide - Version 1.0 - HTML version]
- https://cache2k.org/docs/1.0/user-guide.pdf[User Guide - Version 1.0 - PDF verison]
- https://cache2k.org/docs/1.0/apidocs/cache2k-api/index.html[API - Version 1.0 ]
- https://cache2k.org/docs/1.0/apidocs/cache2k-jmx-api/index.html[JMX-API - Version 1.0]
- https://cache2k.org/docs/1.0/apidocs/cache2k-jcache-api/index.html[JCache API - Version 1.0]

=== Versioning

The JBoss versioning scheme is followed (https://developer.jboss.org/wiki/JBossProjectVersioning).
Furthermore, a Tick-Tock scheme is used to mark development releases. Examples:

1.0.0.Final:: Major version.
1.0.1.Final:: Service release. Should be binary compatible to previous release.
1.1.0.Beta:: *Odd minor version*, development version. A beta version may be used in production, but
 additional features may still change the API and may not completely tested.
1.2.0.Final:: *Even minor version*, stable release, new features and compatible changes to the previous version.
     Not be strictly binary compatible to the previous stable release. Interfaces not meant for
     extension may get new methods.
2.0.0.Final:: New Major version, adds and removes features, may have incompatible changes to the previous version.

=== How to read the documentation

The documentation is intended as a overview guide through the functionality of cache2k and will help
you discover every important feature. At some points rationale or background
information is given. It is not complete. You will find additional information in the API JavaDoc,
in examples, and in the test cases.

A link:user-guide.pdf[cache2k User Guide PDF Version] is available as well.

=== Copyright

The documentation is licensed under the terms of https://creativecommons.org/licenses/by/4.0/[CC BY 4.0].