== About

cache2k is a compact in process cache implementation that has the following main design goals:

Performance:: To achieve high performance cache2k is designed fundamentally different from ground up
  and is leveraging an eviction algorithm that allows concurrent read access without locking overhead.
Ease of use:: Well documented API, provide features beyond standard cache libraries for typical problems,
  the typical configuration should be as small as possible
Compact and modular:: Keep a small core size, additional features may go in separate artifacts

=== Features

List of current features:

 - The fastest cache (compared to other caches available to us), see http:/benchmarks[the benchmarks]
 - Java 6 and Android compatible
 - Leverages Java 8 to increase performance, when available
 - Portable Java code, no use of `sun.misc.Unsafe`
 - Resilience: Smart exception handling
 - Null value support
 - Expiry: duration or point in time
 - Variable expiry per entry
 - CacheLoader with blocking read through
 - AdvancedLoader for smart requests (e.g. if-modified-since)
 - CacheWriter
 - Events
 - Refresh ahead
 - Efficient statistics
 - JMX support
 - Separate, well defined API
 - Complete, single JAR file for deployment (with OSGi support)
 - JCache support

=== Versioning

The JBoss versioning scheme is followed (https://developer.jboss.org/wiki/JBossProjectVersioning).
Furthermore, a Tick-Tock scheme is used to mark development releases. Examples:

1.0.0.Final:: Major version
1.0.1.Final:: Service release. Should be binary compatible to previous release.
1.1.0.Beta:: *Odd minor version*, development version. A beta version may be used in production, but
 additional features may still change the API and may not completely tested.
1.2.0:: *Even minor version*, stable release, new features and compatible changes to the previous version.
     Not be strictly binary compatible to the previous stable release. Interfaces not meant for
     extension may get new methods.
2.0.0.Final:: New Major version, adds and removes features, maybe more incompatible changes to the previous version

=== How to read the documentation

The documentation is intended as a overview guide through the functionality of cache2k and will help
you to discover every important feature. At some points rationale or background
information is given. It is not complete. You will find additional information in the API JavaDoc,
in examples, and in the test cases.
