== About

you are reading the cache2k user guide which walks through all major
feature in a separate section to give an overview.

The following documentation resources are available:

- link:user-guide.html[User Guide (this document) - HTML Version]
- link:user-guide.pdf[User Guide (this document) - PDF Version]

API documentation:

- link:apidocs/cache2k-api/index.html[Cache - API Java Doc]
- link:apidocs/cache2k-addon/index.html[Addon module - API Java Doc]
- link:apidocs/cache2k-jmx/index.html[JMX module - API Java Doc]
- link:apidocs/cache2k-micrometer/index.html[Micrometer module - API Java Doc]
- link:apidocs/cache2k-jcache/index.html[JCache module - API Java Doc]
- link:apidocs/cache2k-spring/index.html[Spring Support - API Java Doc]

=== Versioning

The JBoss versioning scheme is followed (https://developer.jboss.org/wiki/JBossProjectVersioning).
Furthermore, a Tick-Tock scheme is used to mark development releases. Examples:

1.0.0.Final:: Major version.
1.0.1.Final:: Service release. Should be binary compatible to previous release.
1.1.1.Beta:: *Odd minor version*, development version. A beta version may be used in production, but
 additional features may still change the API and may not completely tested.
1.2.0.Final:: *Even minor version*, stable release, new features and compatible changes to the previous version.
     Minor releases may not be strictly binary compatible. Recompilation is needed.
2.0.0.Final:: New Major version, adds and removes features, may have incompatible changes to the previous version.

=== How to read the documentation

The documentation is intended as a overview guide through the functionality of cache2k and will help
you discover every important feature. At some points rationale or background
information is given. It is not complete. You will find additional information in the API JavaDoc,
in examples, and in the test cases.

A link:user-guide.pdf[cache2k User Guide PDF Version] is available as well.

=== Copyright

The documentation is licensed under the terms of https://creativecommons.org/licenses/by/4.0/[CC BY 4.0].