== About

cache2k is a compact in-process cache implementation that has the following main design goals:

Performance:: fundamentally different eviction algorithm to allow fast and lock free reads
Ease of use:: defined API, solve common problems with one configuration option
Compact and modular:: small core size

=== Versioning

The JBoss versioning scheme is followed (https://developer.jboss.org/wiki/JBossProjectVersioning).
Furthermore, a Tick-Tock scheme is used to mark development releases. Examples:

1.0.0.Final:: Major version.
1.0.1.Final:: Service release. Should be binary compatible to previous release.
1.1.0.Beta:: *Odd minor version*, development version. A beta version may be used in production, but
 additional features may still change the API and may not completely tested.
1.2.0.Final:: *Even minor version*, stable release, new features and compatible changes to the previous version.
     Not be strictly binary compatible to the previous stable release. Interfaces not meant for
     extension may get new methods.
2.0.0.Final:: New Major version, adds and removes features, may have incompatible changes to the previous version.

=== How to read the documentation

The documentation is intended as a overview guide through the functionality of cache2k and will help
you discover every important feature. At some points rationale or background
information is given. It is not complete. You will find additional information in the API JavaDoc,
in examples, and in the test cases.

A link:user-guide.pdf[cache2k User Guide PDF Version] is available as well.

=== Copyright

The documentation is licensed under the terms of https://creativecommons.org/licenses/by/4.0/[CC BY 4.0].