[[android]]
== Android

cache2k is compatible with Java 6 and Android. Regular testing is done against API level 16.

[CAUTION]
===============================
This section describes the new jar file structure. For version 1.0 of cache2k dependencies
declaration needs to be different, see https://cache2k.org/docs/1.0/user-guide.html#android[Andriod section Verion 1.0 user guide]
===============================

=== Usage

For cache2k version 1.1 and above, include the following dependencies:

[source,xml]
----
    <dependency>
      <groupId>org.cache2k</groupId>
      <artifactId>cache2k-api</artifactId>
      <version>${cache2k-version}</version>
    </dependency>
    <dependency>
      <groupId>org.cache2k</groupId>
      <artifactId>cache2k-impl</artifactId>
      <version>${cache2k-version}</version>
      <scope>runtime</scope>
    </dependency>
----

=== XML Configuration

XML configuration is usable in Android as well. The build-in XML Pull Parser is
used instead of Stax. The XML configuration code will be removed via Proguard, if not used. See below.

=== Proguard Rules

The `cache2k-impl` contains code relevant for server based software or enterprise software that is
usually not needed within Android. One example is the exposure of statistics via JMX. The code base is
modular, and code needed within server environments is usually not loaded whithin Android applications.
To minimize the footprint of the application the unused code can be removed via Proguard rules.

[source]
----
# mandatory proguard rules for cache2k
-dontwarn org.slf4j.**
-dontwarn javax.cache.**
-keep interface org.cache2k.spi.Cache2kCoreProvider
-keep public class * extends org.cache2k.spi.Cache2kCoreProvider

# optional proguard rules for cache2k, to keep XML configuration code
# if only programmatic configuration is used, these rules may be ommitted
-keep interface org.cache2k.core.spi.CacheConfigurationProvider
-keep public class * extends org.cache2k.core.spi.CacheConfigurationProvider
-keepclassmembers public class org.cache2k.impl.xmlConfiguration.ConfigurationContext {
    public void set*(...);
    public ** get*();
}
-keepclassmembers public class org.cache2k.configuration.Cache2kConfiguration {
    public void set*(...);
    public ** get*();
}
----
