[[expiry-and-refresh]]
== Expiry and Refresh

A cached value may expire after some specified time. When expired, the value is not
returned by the cache any more. The cache may be instructed to do an automatic
reload of an expired value, this is called _refresh ahead_.

Expiry does not mean that a cache entry is removed from the cache. The actual
removal from the cache may lag behind the time of expiry.

=== Specifying an Expiry Duration

Expiry after an entry is created or modified can be specified via the `expireAfterWrite` parameter.
This is also known as _time to live_. It is possible to specify different expiry values for
created or modification with a custom `ExpiryPolicy`.

[NOTE]
_Expiry after access_ or _time to idle_ is not supported, since it would compromise the high performance
of cache2k. There is seldom a functional requirement for TTI, but it is used
very often to minimize memory consumption in times of low activity. How a similar feature can be
constructed that, at the same time, is not counter productive for performance needs further research.
For discussion, see: https://github.com/cache2k/cache2k/issues/39[GH 39]

=== Variable Expiry

Each entry may have a different expiry time. This can be achieved by specifying an `ExpiryPolicy`.
The `ExpiryPolicy` calculates a point in time, when a value expires. The configuration parameter
`expireAfterWrite` is used as a maximum value.

=== Lagging Expiry

In standard operation time checks when accessing the entry are saved and the actual expiry of an entry
may lag behind, meaning that entries that should expire are visible some milliseconds longer.

=== Sharp Expiry

In case there is a business requirement that data becomes invalid or needs refreshed at a defined point
in time the parameter `sharpExpiry` can be enabled. This will cause that the expiry happens exactly at
the point in time determined by the expiry policy. For more details see the JavaDoc or
`Cache2kBuilder.sharpExpiry` and `ExpiryPolicy`.

If _sharp expiry and refresh ahead_ is both enabled, the contract of refresh ahead is relaxed.
The resulting semantics will be:

 - Entries will expire exactly at the specified time
 - A refresh starts at expiry time
 - `contains()` is `false`, if the entry is expired and not yet refreshed
 - A `get()` on the expired entry will stall until refreshed

Sharp expiry and normal, lagging expiry can be combined. For example, if the parameter `expiryAfterWrite` and an
`ExpiryPolicy` is specified and `sharpExpiry` is enabled. The sharp expiry will be used for the
time calculated by the `ExpiryPolicy`, but the duration in `expireAfterWrite` is used if this will be sooner.
If the expiry is result of a duration calculation via `expireAfterWrite` sharp expiry of the entry will not be
enabled.

=== Loader Exceptions and Expiry

When an expiry duration is specified via `expireAfterWrite`, resilience features are automatically
active. See the resilience chapter for details.

=== Resetting the Expiry of a Cache Value

The expiry value can be reset with the method `Cache.expireAt(key, time)`. Some special values exist:

.`Cache.expireAt()` constants
[width="70",options="header"]
,===
constant,meaning
`Expiry.NOW`, The value expires immediately. An immediate load is triggered if refreshAhead is enabled.
`Expiry.REFRESH`, An immediate load is triggered if refreshAhead is enabled. If loading is not possible the value expires.
`Expiry.ETERNAL`, keep indefinitly or to a maximum of whats set with via `expireAfterWrite`
,===

It is possible to atomically examine a cached entry and update its expiry with the `EntryProcessor` and
`MutableCacheEntry.setExpiry()`.

=== Wall Clock and Clock Skew

For timing reference the Java `System.currentTimeMillis()` is used. As with any application that relies on
time, it is good practice that the system clock is synchronized with a time reference. When the system time
needs to be corrected, it should adapt slowly to the correct time and keep continuously ascending.

In case a clock skew happens regularly a premature or late cache expiry may cause troubles. It is possible
to do some countermeasures. If the time decreases, entries may expire more early. This can be detected and with the
`AdvancedCacheLoader` the previously loaded value can be reused. If there is a time skew forward, expiry can
be triggered programmatically with `expireAt()`.
