[[jcache]]
== JCache

cache2k supports the JCache API standard. The implementation is compatible to the JSR107 TCK.

=== Maven Dependencies

Additionally to the normal cache2k dependencies the following dependencies need to be added:

[source,xml]
----
    <dependency>
      <groupId>org.cache2k</groupId>
      <artifactId>cache2k-all</artifactId>
      <version>${cache2k-version}</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.cache2k</groupId>
      <artifactId>cache2k-jcache</artifactId>
      <version>${cache2k-version}</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>javax.cache</groupId>
      <artifactId>cache-api</artifactId>
      <version>1.1.0</version>
    </dependency>
----

=== Getting Started with the JCache API

Since cache2k is JCache compatible, any available JCache introduction can be used for the
first steps. The following online sources are recommended:

 - https://dzone.com/refcardz/java-caching
 - https://www.youtube.com/watch?v=EugtmOaZn9w

=== Configuration

JCache does not define a complete cache configuration, for example, configuring the
cache capacity is not possible. To specify a meaningful cache configuration, the cache2k configuration mechanism
needs to be utilized.

==== Programmatic Configuration

To create a JCache with an additional cache2k configuration the interface `ExtendedConfiguration`
and the class `MutableExtendedConfiguration` is provided. The configuration classes are available in
separate API packages, that need to be included in the compile scope:

[source,xml]
----
    <dependency>
      <groupId>org.cache2k</groupId>
      <artifactId>cache2k-api</artifactId>
      <version>${cache2k-version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.cache2k</groupId>
      <artifactId>cache2k-jcache-api</artifactId>
      <version>${cache2k-version}</version>
    </dependency>
----

Example usage:

[source,java]
----
    CachingProvider p = Caching.getCachingProvider();
    CacheManager cm = p.getCacheManager();
    Cache<Long, Double> cache = cm.createCache("aCache", ExtendedMutableConfiguration.of(
      new Cache2kBuilder<Long, Double>(){}
        .entryCapacity(10000)
        .expireAfterWrite(5, TimeUnit.MINUTES)
    ));
----

When a cache2k configuration is provided, the default behavior is not 100% JCache compatible any more, because
the defaults of cache2k apply. Strict JCache behavior can be enabled again, if needed. The areas of difference
are explained below:

Expiry:: With pure JCache configuration the expiry is set to sharp expiry by default for maximum compatiblity. When the
   cache2k configuration is used, sharp expiry is off and need to be enabled explicitly.
`Configuration.isStoreByValue`:: When the cache2k configuration is active the parameter will be ignored, if true.
   Store by value semantics can enabled again in the JCache configuration section of cache2k
   `JCacheConfiguration.Builder.copyAlwaysIfRequested`. See example below how to specify the additional parameters.

The JCache configuration and the cache2k configuration may have settings that control the same
feature, for example expiry. In this case the two configurations need to be merged and conflicting settings
have to be resolved. The policy is as follows:

Expiry settings:: Settings in cache2k configuration take precedence. A configured expiry policy in the standard
  JCache `CacheConfiguration` will be ignored if either `expiryAfterWrite` or `expiryPolicy` is specified in
  the cache2k configuration.
Loader and Writer:: Settings in JCache configuration take precedence. If a loader or a writer is specified in the
  JCache `CacheConfiguration` the setting in the cache2k configuration is ignored.
Event listeners:: Registered listeners of both configurations will be used.

=== Control Additional JCache Semantics

The JCache implementation has additional options that control its semantics. These options are available in
the `JCacheConfiguration` configuration section, which is provided by the `cache2k-jcache-api` module.

Example usage:

[source,java]
----
    CachingProvider p = Caching.getCachingProvider();
    CacheManager cm = p.getCacheManager();
    Cache<Long, Double> cache = cm.createCache("aCache", ExtendedMutableConfiguration.of(
      new Cache2kBuilder<Long, Double>(){}
        .entryCapacity(10000)
        .expireAfterWrite(5, TimeUnit.MINUTES)
        .with(new JCacheConfiguration.Builder()
          .copyAlwaysIfRequested(true)
        )
    ));
----

The example enables store by value semantics again and requests that keys and values are copied when passed
to the cache or retrieved from the cache.

=== Implementation Details

==== Semantic Changes Since JCache 1.0

The JCache specification team has made some changes to its TCK since the original 1.0 release.
The cache2k implementation already adheres to the latest corrected TCK 1.1.

.Corrected or Enforced JSR107 Semantics in TCK 1.1
[width="70",options="header"]
,===
Affected Component,JSR107 GitHub issue
`EntryProcessorException`, https://github.com/jsr107/jsr107tck/issues/85
Customizations may implement `Closeable`, https://github.com/jsr107/jsr107tck/issues/100
`CacheEntry.getOldValue()` for removed event, https://github.com/jsr107/jsr107spec/issues/391
Statistics of `Cache.putIfAbsent()`, https://github.com/jsr107/jsr107tck/issues/63
`CacheManager.getCacheNames()`, https://github.com/jsr107/jsr107tck/issues/87
`CacheManager.getCache()`, https://github.com/jsr107/jsr107spec/issues/340
JMX statistics,  https://github.com/jsr107/jsr107tck/issues/83
,===

==== Expiry Policy

If configured via cache2k mechanisms, the cache2k expiry settings take precedence.

If a JCache configuration is present for the expiry policy the policies `EternalExpiryPolicy`,
`ModifiedExpiredPolicy` and `CreatedExpiredPolicy` will be handled efficiently. A custom
implementation of the `ExpiryPolicy` will induce additional operational overhead.

The use of `TouchedExpiryPolicy` or `ExpiryPolicy.getExpiryAccess()` is discouraged. Test performance
carefully before use in production.

==== Store by Value

If configured via cache2k mechanisms, store by value semantics are not provided by cache2k by default.
Instead the usual in process semantics are provided. Applications should not rely on the fact
that values or keys are copied by the cache in general.

For heap protection cache2k is able to copy keys and values. This can be enabled via the parameter
`JCacheConfiguration.setCopyAlwaysIfRequested`, see the configuration example above.

==== Loader exceptions

cache2k is able to cache or suppress exceptions, depending on the situation and the configuration.

If an exception is cached, the following behavior can be expected:

  * Accessing the value of the entry, will trigger an exception
  * `Cache.containsKey()` will be true for the respective key
  * `Cache.iterator()` will skip entries that contain exceptions

==== Listeners

Asynchronous events are delivered in a way to achieve highest possible parallelism while retaining the event
order on a single key. Synchronous events are delivered sequentially.

==== Entry processor

Calling other methods on the cache from inside an entry processor execution (reentrant operation), is not supported.
The entry processor should have no external side effects. To enable asynchronous operations, the execution
may be interrupted by a `RestartException` and restarted.

==== Cache.getConfiguration()

It is not possible to retrieve the additional effective cache2k configuration with this method.

=== Performance

Using the JCache API does not deliver the same performance as when the native cache2k API is used.
Some design choices in JCache lead to additional overhead, for example:

 - Event listeners are attachable and detachable at runtime
 - Expiry policy needs to be called for every access
 - Store-by-value semantics require keys and values to be copied

=== Compliance Testing

To pass the TCK tests on statistics, which partially enforce that statistic values need to be updated immediately.
For compliance testing the following system properties need to be set:

- `org.cache2k.core.HeapCache.Tunable.minimumStatisticsCreationTimeDeltaFactor=0`
- `org.cache2k.core.HeapCache.Tunable.minimumStatisticsCreationDeltaMillis=-1`

Since immediate statistics update is not a requirement by the JSR107 spec this is needed for testing purposes only.
