[[loading-read-through]]
== Loading / Read Through

In read through operation the cache will fetch the value by itself when the value is retrieved, for
example by `Cache.get()`. This is also called a _loading cache_ or a _self populating cache_.

=== Benefits of Read Through Operation

When caching reads, using the cache in read through operation has several advantages:

 - No boilerplate code as in cache aside
 - Data source becomes configurable
 - Blocking load operations for identical keys, protection against the cache stampede (See https://en.wikipedia.org/wiki/Cache_stampede[Wikipedia: Cache Stampede])
 - Automatic refreshing of expired values (refresh ahead)
 - Build-in exception handling like suppression and retries (see <<resilience,Resilience>> chapter)

=== Defining a Loader

A loader is defined by implementing the abstract class `CacheLoader`.
See the <<getting-started,Getting Started>> example about read through.

[source,java]
----
interface CacheLoader<K, V> {
  V load(K key) throws Exception;
}
----

The loader actions may only depend on the input key parameter. In case the load operation
will yield an exception it may be passed on to the cache. How exceptions are handled by the cache
is defined by the resilience policy and explained in the <<resilience,Resilience chapter>>.

The JavaDoc about the link:{cache2k_docs}/apidocs/cache2k-api/index.html?org/cache2k/io/CacheLoader.html[`CacheLoader`]
contains additional details.

=== Advanced Loader

For more sophisticated load operations the `AdvancedCacheLoader` is available.

[source,java]
----
interface AdvancedLoader<K, V> {
  V load(K key, long currentTime, CacheEntry<K,V> currentEntry) throws Exception;
}
----

The information of the current entry can be used to optimize the data request. A typical
example is the optimization of HTTP requests and use the request header `If-Modified-Since`.

The JavaDoc about the link:{cache2k_docs}/apidocs/cache2k-api/index.html?org/cache2k/io/AdvancedCacheLoader.html[`AdvancedCacheLoader`]
contains additional details.

=== Invalidating

In case the data was updated in the external source, the current cache content
becomes invalid. To notify the cache and eventually update the cached value
several options exist.

`Cache.remove(key)`::

Invalidating an entry with `Cache.remove()` will cause the entry to be removed from the cache ultimately.
The next time the entry is requested with `Cache.get(key)` the cache will invoke the loader (if defined).
In case the loader yields an exception, this exception will be propagated to the application since there
is no previous value for fallback. `Cache.remove(key)` is useful if the data is outdated and old data is
not allowed to be delivered. `Cache.remove()` will also invoke `CacheWriter.delete()`, if specified.
Priority is on data consistency.

`Cache.expireAt(key, Expiry.NOW)`::

The entry is expired immediately.

`Cache.expireAt(key, Expiry.REFRESH)`::

When invalidating an entry via `Cache.expireAt(key, Expiry.REFRESH)` the loader
gets invoked instantly if refresh ahead is enabled. If the loader is invoked, the current value
will stay visible until the updated value is available. If the loader cannot be invoked, the entry is
expired. The operation will have no effect, if there is no cached entry associated with the key. The value
is still available in the cache as fallback if a loader exception occurs. This variant is the better
choice if outdated values are allowed to be visible and the cache should continuously serve data.
Priority is on availability.

=== Transparent Access

When using the cache in read through and/or in write through operation, some methods on the
cache will often be misinterpreted and present pitfalls. For example, the method
`Cache.containsKey` will not return true when the value exists in the system of authority,
but only reflects the cache state.

To prevent pitfalls a reduced set of interfaces is available:
{api_link}/KeyValueSource.html[`KeyValueSource`],
{api_link}/AdvancedKeyValueSource.html[`AdvancedKeyValueSource`] and
{api_link}/KeyValueStore.html[`KeyValueStore]` are available. These interfaces only contain
methods that act transparently when a loader or writer is defined.

