[[refresh-ahead]]
== Refresh Ahead

With refresh ahead (or background refresh), in a read through configuration,
values about to expire will be refreshed automatically by the cache.

=== Setup

Refresh ahead (or background refresh) can be enabled via `refreshAhead()` switch.
The number of threads used for refreshing is configured by `loaderThreadCount()`.
A (possibly shared) thread pool for refreshing can be configured via `prefetchExecutor()`.

=== Semantics

The main purpose of refresh ahead is to ensure that the cache contains fresh data
and that an application never is delayed when data expires and needs a reload.
This leads to several compromises: Expired values will be visible until the new
data is available from the load operation, more then the needed requests will be send
to the loader.

After the expiry time of a value is reached, the loader is invoked to fetch a fresh value.
The old value will be returned by the cache, although it is expired, and will be replaced
by the new value, once the loader is finished. When a refresh is needed and not enough loader
threads are available, the value will expire immediately and the next `get()` request
will trigger the load.

Once refreshed, the entry is in a trail period. If it is not accessed until the next
expiry, no refresh will be done, the entry expires and will be removed from the cache.
This means that the time an entry stays within the trail period is determined by the
configured expiry time or the the `ExpiryPolicy`.

NOTE: Refresh ahead only works together with the methods invoking the loader, for example
`get()` and `getAll()`. After a value is refreshed, an entry will not be visible with
`containsKey` or `peek`. The first call to `get()` or `load()` on a previously refreshed
item will make the loaded value available in the cache.

=== Sharp Timeout vs. Refresh Ahead

The setting `sharpTimeout` conflicts with the idea of refresh ahead. When using
refresh ahead and sharp timeout in combination, the value will expire at the specified
time and the background refresh is initiated. When the application requests the value
between the expiry and before the new value is loaded, it blocks until the new value
is available. Avoid using sharp timeout in combination with refresh ahead. Sharp timeout can also applied
on a per entry basis only when needed.

[NOTE]
Combining sharp expiry, lagging expiry and refresh ahead, leads to an operation mode that
cannot guarantee the sharp expiry contract under all circumstances. A an ongoing load operation
is not finished before a sharp expiry time, non fresh data will become visible.

=== Rationale: No separate refresh timing parameter?

Caches supporting refresh ahead typically have separate configuration parameters for its timing.
In cache2k, refreshing is done when the value would expire, which is controlled by the expiry policy
and `expireAfterWrite` parameter. Why? It should be possible to enable refresh ahead with a single
switch. Refreshing and expiring are two sides of the same coin: When expired, we need to refresh.

=== Future Outlook

More options to control refreshing and the trail period are added in the next releases.

The effects on the event listeners and statistics when refreshing may change in the future.
