[[resilience-and-exceptions]]
[[resilience]]
== Exceptions and Resilience

This section documents the behavior since cache2k version 2.0.

In a read through mode (with a `CacheLoader`) the cache can be configured to tolerate temporary
loader failures with the `ResiliencePolicy`.

Without a specified `ResiliencePolicy` the cache  will only keep successfully loaded values.
If a load yields an exception the load is retried immediately when the value is requested again.
With the `ResiliencePolicy` it is possible to keep an exception in the cache for some time
and stop sending new requests for that particular key, to not overflow a faulty data source
and minimize local resource and network usage. It is also possible to suppress exception for
some time, in case a loaded value is present from a previous load.

The core of cache2k contains all the infrastructure to deal with exceptions. Whenever a cached
value is requested, e.g. via `Cache.get()`, `CacheEntry.get()` and also `Cache.peek()` the cache
would rethrow a previous loader exception. Each cache call generates a would generate a new
`CacheLoaderException` which contains the original exceptions as cause. This can be controlled
via the `ExceptionPropagator`. In case an exception was thrown by the loader the entry contains
a `LoadExceptionInfo` which contains useful information for decision making in the
`ResiliencePolicy` or to propagate via the `ExceptionPropagator`.

=== Using UniversalResiliencePolicy

cache2k ships with a `ResiliencePolicy` implementation called `UniversalResiliencePolicy` that
is useful in typical scenarios. The rest of this chapter describes the usage of
`UniversalResiliencePolicy`.

To learn more on how to implement your own policy, study the Java Doc of
`ResiliencePolicy` and the source code of the `UniversalResiliencePolicy`.
Rather then reading the documentation here, it might be easier to look
at the source code and examples. Alternatively, start and experiment
with the configuration examples at the end of the chapter.

Add the `cache2k-addon` module to your application:

[source,xml]
----
        <dependency>
            <groupId>org.cache2k</groupId>
            <artifactId>cache2k-addon</artifactId>
            <version>${cache2k-version}</version>
        </dependency>
----

To enable the policy with the buider use:

[source,java]
----
      builder.setup(UniversalResiliencePolicy::enable)
----

To set additional parameters to the policy:

[source,java]
----
      builder.setupWith(UniversalResiliencePolicy::enable, b -> b
        .resilienceDuration(5, TimeUnit.SECONDS)
      )
----

Depending on preference the policy can also enabled by default for all caches and
then disabled on individual cache basis.

==== UniversalResiliencePolicy Default Behavior

When enabled and without additional parameters, the `UniversalResiliencePolicy` starts
caching and suppressing exceptions in read through operation, when a expiry time
(`expireAfterWrite`) is set.

A cached exception will be rethrown every time the key is accessed. After some
time passes, the loader will be called again. A cached exception can be spotted by the expiry time
in the exception text, for example:

----
org.cache2k.integration.CacheLoaderException: expiry=2016-06-04 06:08:14.967, cause: java.lang.NullPointerException
----

Cached exceptions can be misleading, because you may see 100 exceptions in your log, but only
one was generated from the loader. That's why the expiry of an exception is typically shorter then
the configured expiry time. When a previous value is available a subsequent loader exception
is suppressed for a short time.

If no expiry is specified or `eternal(true)` is specified, all exceptions will be propagated to
the client. The loader will be called immediately again, if the key is requested again.
This is identical to no policy.

==== Expiry and resilience duration

When an expiry time is specified, the `UniversalExpiryPolicy` enables the resilience features.

If a load yields an exception and there is data in the cache: The exception will not be
propagated to the client, and the cache answers requests with the current cache content.
Subsequent reload attempts that yield an exception, will also be _suppressed_, if the time span to the
first exception is below the resilience duration setting.

If the loader produces subsequent exceptions that is longer then the resilience duration,
the exception will be _propagated_. The resilience duration can be set with the parameter
`resilienceDuration`, if not set explicitly it is identical to the `expiryAfterWrite`
time span.

=== Retry

After an exception happens the `UniversalResiliencePolicy` will do a retry to load the value again.
The retry is started after the configured retry interval (`retryInterval`), or, if not
explicitly configured after 5% of the resilience duration. The load is started when
the client accesses the value again, or the cache is doing this by itself if `refreshAhead`
is enabled.

To keep the system load in limits in the event of failure, the duration between each retry
increases according to an _exponential backoff_ pattern by the factor of 1.5.
Each duration is further randomized between one half and the full value.
For example, an `expireAfterWrite` set to 200 seconds will lead to an initial retry
time of 10 seconds. If exceptions persist the retry time will develop as follows:

.Retry intervals with exponential backoff starting at 10 seconds
[width="70",options="header"]
,===
retry after
10 seconds
15 seconds
22.5 seconds
33.75 seconds
,===

When reaching the configured expiry the cache will retry at this time interval and
not increase further. The start retry interval and the maximum retry interval can
be specified by `retryInterval` and `maxRetryInterval`.

=== Exception Propagation

If an exception cannot be suppressed, it is propagated to the client immediately.
The retry attempts follow the same pattern as above.

When propagated, a loader exception is wrapped and rethrown as `CacheLoaderException`.
A loader exception is potentially rethrown multiple times, if the retry time is not
yet reached. In this situation a rethrown exception contains the text `expiry=<timestamp>`.
This behavior can be customized by the `ExceptionPropagator`.

=== Invalidating and reloading

An application may need to invalidate a cache entry, so the cache will invoke the loader
again the next time the entry is requested. How the value should be invalidated depends on
the usage scenario and whether availability or consistency has to be priority.

To be able to use the resilience features and increase availability in the event of failure
the method `expireAt` should be preferred for invalidation. See the detailed discussion in the
loading chapter.

=== Entry Status and `containsKey`

In case an exception is present, the method `containsKey` will return `true`, the methods
`putIfAbsent` and `computeIfAbsent` act consequently. This means `pufIfAbsent` can not be used
to overwrite an entry in exception state with a value.

To examine the state of an entry, e.g. whether it contains a value or exception, the method
`Cache.peekEntry` can be used. To examine the state of an entry and modify it, the entry processor
can be used.

=== Configuration options

To customize the behavior the following options exist. In the base configuration:

expireAfterWrite:: Time duration after insert or updated an cache entry expires
resiliencePolicy:: Sets a custom resilience policy to control the cache behavior in the presence of exceptions
exceptionPropagator:: Sets a custom behavior for exception propagation
refreshAhead:: Either the option `refreshAhead` or `keepDataAfterExpired` must be enabled to do exception suppression if an expiry is specified
keepDataAfterExpired:: Either the option `refreshAhead` or `keepDataAfterExpired` must be enabled to do exception suppression if an expiry is specified

The `UniversalResiliencePolicy` has additional parameters in `UniversalResilienceConfig`:

resilienceDuration:: Time span the cache will suppress loader exceptions if a value is available from
                     a previous load. Defaults to `expiredAfterWrite`
minRetryInterval:: The minimum interval after a retry attempt is made. Defaults to `0`
maxRetryInterval:: The maximum interval after a retry attempt is made. Defaults to `resilienceDuration`
retryInterval:: Initial interval after a retry attempt is made. Defaults to 10% (or `retryPercentOfResilienceDuration`) of `mayRetryInterval`, or a minimum of 2 seconds.
backoffMultiplier:: Factor to increase retry time interval after a consequtive failure

The timing parameters may be derived from `expireAfterWrite`. This is controlled by:

retryPercentOfResilienceDuration:: Percentage from `expireAfterWrite` to use for the `retryInterval`, default is 10%


=== Examples

==== No expiry

Values do not expire, exceptions are not suppressed. After an exception, the next `Cache.get()` will trigger
a load.

[source,java]
----
    Cache<Integer, Integer> c = new Cache2kBuilder<>() {}
      .eternal(true)
      /* ... set loader ... */
      .build();
----

==== Expire after 10 minutes with resilience

Values expire after 10 minutes. Exceptions are suppressed for 10 minutes
as well, if possible. A retry attempt is made after 1 minute. If the cache
continuously receives exceptions for a key, the retry intervals are exponentially
increased up to a maximum interval time of 10 minutes.

The `UniversalResiliencePolicy` derives its parameters from the `expireAfterWrite` setting.

[source,java]
----
    Cache<Integer, Integer> c = new Cache2kBuilder<>() {}
      .expireAfterWrite(10, TimeUnit.MINUTES)
      .keepDataAfterExpired(true)
      .setup(UniversalResiliencePolicy::enable)
      /* ... set loader ... */
      .build();
----

==== Reduced suppression time

Expire entries after 10 minutes. If an exception happens we do not want
the cache to continue to service the previous (and expired) value for too long. In this scenario
it is preferred to propagate an exception rather than serving a potentially outdated value.
On the other side, there may be temporary outages of the network for a maximum of 30 seconds
we like to cover for.

[source,java]
----
    Cache<Integer, Integer> c = new Cache2kBuilder<Integer, Integer>() {}
      .expireAfterWrite(10, TimeUnit.MINUTES)
      .setupWith(UniversalResiliencePolicy::enable, b -> b
        .resilienceDuration(30, TimeUnit.SECONDS)
      )
      .keepDataAfterExpired(true)
      /* ... set loader ... */
      .build();
----

==== Cached exceptions

No suppression, because values never expire. The only way that a reload can be triggered
is with a reload operation. In this case we do not want suppression, unless
specified explicitly. The loader is not totally reliable, or a smart developer
uses an exception to signal additional information. If exceptions occur, the cache
should not be ineffective and keep exceptions and defer the next retry for 10 seconds.
For requests between the retry interval, the cache will rethrow the previous exception.
The retry interval does not increase, since a maximum timer interval is not specified.

[source,java]
----
   Cache<Integer, Integer> c = new Cache2kBuilder<Integer, Integer>() {}
      .eternal(true)
      .setupWith(UniversalResiliencePolicy::enable, b -> b
        .retryInterval(10, TimeUnit.SECONDS)
      )
      /* ... set loader ... */
      .build();
----

=== Debugging

The cache has no support for logging exceptions. If this is needed, it can be achieved
by an adaptor of the `CacheLoader`.

=== Statistics

The statistics expose counters for the total number of received load exceptions and the number
of suppressed exceptions.
