[[spring]]
== Spring Framework

=== Enable Cache2k Spring Support

To use cache2k in you Spring project, add the following libraries:

[source,xml,subs="attributes+"]
----
    <properties>
      <cache2k-version>{cache2k_version}</cache2k-version>
    </properties>

    <dependency>
      <groupId>org.cache2k</groupId>
      <artifactId>cache2k-api</artifactId>
      <version>${cache2k-version}</version>
    </dependency>
    <dependency>
      <groupId>org.cache2k</groupId>
      <artifactId>cache2k-core</artifactId>
      <version>${cache2k-version}</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.cache2k</groupId>
      <artifactId>cache2k-spring</artifactId>
      <version>${cache2k-version}</version>
    </dependency>
----

To enable your application to use caching via cache2k, typically define a `CachingConfig` class
which makes the `SpringCache2kCacheManager` available:

[source,java]
----
@Configuration
@EnableCaching
public class CachingConfig {

  @Bean
  public CacheManager cacheManager() {
    return new SpringCache2kCacheManager();
  }

}
----

By default, there needs to be a cache configuration (see below) for every used cache. If
the cache manager should return a cache, even the name is unknown, then use `setAllowUnknownCache(true)`.
See link:{cache2k_docs}/apidocs/cache2k-spring/index.html?org/cache2k/extra/spring/SpringCache2kCacheManager.html[`SpringCache2kCacheManager API documentation`] for a complete method reference.

=== XML Based Setup

When enabled as shown above, the cache2k cache manager will create caches as requested by the application.
For the default cache manager, the cache configuration is looked up in the file `cache2k.xml`.
For further details see the <<xml-configuration,Configuration via XML>> chapter.

=== Programmatic Setup

It is possible to configure various caches with different configuration parameters via the builder pattern of cache2k:

[source,java]
----
  @Bean
  public CacheManager cacheManager() {
    return new SpringCache2kCacheManager()
      .defaultSetup(b->b.entryCapacity(2000))
      .addCaches(
        b->b.name("countries"),
        b->b.name("test1").expireAfterWrite(30, TimeUnit.SECONDS).entryCapacity(10000),
        b->b.name("anotherCache").entryCapacity(1000)).permitNullValues(true);
  }
----

The makes three caches available. The method `addCaches` adds one or more caches by modifying a builder with the
specified parameters. The method `defaultSetup` can be used to apply default settings which should be
used for all caches. It is possible to mix the programmatic setup with the XML configuration of cache2k, in this case
the order of application is:

- XML setup default section
- `SpringCache2kCacheManager.defaultSetup`
- `SpringCache2kCacheManager.addCaches`
- XML setup cache section

Cache2k supports multiple cache managers. Caches used within the Spring DI context, could be separated into
another cache manager, e.g. with `new SpringCache2kCacheManager("spring")`.

For further details, see link:{cache2k_docs}/apidocs/cache2k-spring/index.html?org/cache2k/extra/spring/SpringCache2kCacheManager.html[`SpringCache2kCacheManager API documentation`].

=== Multiple Application Contexts

In testing scenarios multiple applications contexts are created. To avoid conflicts its a good idea to have
separate cache managers in each application context. Within testing a feasible trick is to use the hash code
of the configuration object to create a unique name for the caching manager.

[source,java]
----
  @Bean
  public CacheManager cacheManager() {
    return new SpringCache2kCacheManager("spring-" + hashCode());
  }
----

However, this makes it impossible to use the cache2k external XML configuration since the configuration
file name is derived from the manager name.

=== Spring Bean XML Configuration

For completeness, together with the `Cache2kConfig` bean, it is also possible to use the Spring bean XML configuration.

=== Null Value Support

The cache abstraction of Spring is supporting `null` values. To support this a cache used by Spring is
build with `Cache2kBuilder.permitNullValues(true)` by default. See <<null-values,Null Values>>.

In case the application does not store `null` values its good practise to include
`permitNullValues(false)` in the cache configuration, to document and enforce this fact.

=== Resources

More information on the Spring Cache abstraction can be found here:

- https://docs.spring.io/spring/docs/current/spring-framework-reference/integration.html#cache[Cache Abstraction - Spring Framework Reference]
- https://www.foreach.be/blog/spring-cache-annotations-some-tips-tricks[Spring cache annotations: some tips & tricks - foreach.be blog]
