== Getting started

=== Obtaining cache2k

The latest cache2k version is available on maven central. The recommended way to include it
in your project is to add the following dependencies:

[source,xml,subs="attributes+"]
----
    <properties>
      <cache2k.version>{cache2kversion}</cache2k.version>
    </properties>

    <dependencies>
        <dependency>
          <groupId>org.cache2k</groupId>
          <artifactId>cache2k-api</artifactId>
          <version>${cache2k.version}</version>
          <scope>compile</scope>
        </dependency>
        <dependency>
          <groupId>org.cache2k</groupId>
          <artifactId>cache2k-all</artifactId>
          <version>${cache2k.version}</version>
          <scope>runtime</scope>
        </dependency>
     </dependencies>
----

This will add the single `cache2k-all` JAR file to your application deliverable. For compiling and development
 the `cache2k-api` is included which contains API classes meant for cache clients and no implementation classes.
 Everything inside the API is kept stable and is well documented.

The above requires at least a `Java SE 6` compatible runtime. For inclusion with Android, see the Android chapter.

=== Using a Cache

For starting with cache2k, let's construct a cache that maps one of our frequent flight routes to our airline of choice.

[source,java]
----
    Cache<String, String> cache = new Cache2kBuilder<String, String>() {}
      .name("routeToAirline")
      .eternal(true)
      .entryCapacity(100)
      .build();
    // populate with our favorites
    cache.put("MUC-SFO", "Yeti Jet");
    cache.put("SFO-LHR", "Quality Air");
    cache.put("LHR-SYD", "Grashopper Lifting");
    // query the cache
    String route = "LHR-MUC";
    if (cache.containsKey(route)) {
      System.out.println("We have a favorite airline for the route " + route);
    } else {
      System.out.println("We don't have a favorite airline for the route " + route);
    }
    String airline = cache.peek(route);
    if (airline != null) {
      System.out.println("Let's go with " + airline);
    } else {
      System.out.println("You need to find one yourself");
    }
----

To obtain the cache a new `Cache2kBuilder` is created, mind the untypical `{}`. There are a dozens of
options that can alter the behavior of a cache. In the example above the cache gets a name and is instructed
to keep entries forever via `eternal(true)`. A name needs to be unique and may be used to find and apply additional
configuration parameters and to make statistics available via JMX. See the JavaDoc of `Cache2kBuilder.name()`.
Building a cache with the same name twice leads to an error.

The cache has a maximum capacity of 100 entries. When the limit is reached an entry is automatically removed that
 is not used very often. This is called eviction.

In the further example `Cache.put` is used to store values. The cache content is queried with `Cache.peek` and
`Cache.containsKey`.

=== Cache Aside

Let's consider we have an operation called `findFavoriteAirline`, that checks all our previous flights
and find the airline we liked the most. If we never did fly on that route it asks all our friends.
 Of course this is very time consuming, so we first ask the cache, whether something for that flight
 route is already known, if not we call the expansive operation.

[source,java]
----
    Cache<String, String> routeToAirline = new Cache2kBuilder<String, String>() {}
      .name("routeToAirline")
      .build();

    private String findFavoriteAirline(String origin, String destination) {
      // expansive operation to find the best airline for this route
      // for example, ask all friends...
    }

    public String lookupFavoirteAirline(String origin, String destination) {
      String route = origin + "-" + destination;
      String airline = routeToAirline.peek(route);
      if (airline == null) {
        airline = findFavoriteAirline(origin, destination);
        routeToAirline.put(route, airline);
      }
      return airline;
    }
----

The above pattern is called _cache aside_.

=== Loading / Read Through

An alternative way to use the cache is the so called _read through_ operation. The cache configuration
gets extended by a loader, so the cache knows how to retrieve missing values.

[source,java]
----
  Cache<String, String> routeToAirline = new Cache2kBuilder<String, String>() {}
    .name("routeToAirline")
    .loader(new CacheLoader<String, String>() {
      @Override
      public String load(final String key) throws Exception {
        String[] port = key.split("-");
        return findFavoriteAirline(port[0], port[1]);
      }
    })
    .build();

  private String findFavoriteAirline(String origin, String destination) {
    // expansive operation to find the best airline for this route
  }

  public String lookupFavoirteAirline(String origin, String destination) {
    String route = origin + "-" + destination;
    return routeToAirline.get(route);
  }
----

Now we use `Cache.get` to request a value from the cache, which transparently invokes
the loader and populates the cache, if a value is missing. Using a cache in read through
mode has various advantages:

- No boilerplate code as in cache aside
- Protection against the cache stampede (See https://en.wikipedia.org/wiki/Cache_stampede[Wikipedia: Cache Stampede])
- Automatic refreshing of expired values (refresh ahead)
- Build-in exception handling like suppression and retries (see Resilience chapter)

=== Null Values

The simple example has a major design problem. What happens if no airline is found? Typically caches don't allow
`null` values. When you try to store or load a `null` value into cache2k you will get a `NullPointerException`.
Sometimes it is better to avoid `null` values, in our example we could return a list of favorite airlines which may
 be empty.

In case a `null` value is the best choice, it is possible to store it in cache2k by enabling it with
`permitNullValues(true)`. More on nulls, see the separate chapter.

=== Keys

In the example the key is constructed by concatenating the origin and destination airport. This is ineffective for
several reasons. The string concatenation allocates two temporary objects (the `StringBuilder` and
its character array); if we need the two ports again we have to split the string again. A better way
is to define a dedicated class for the cache key that is a tuple of origin and destination.

[source,java]
----
  public final class Route {
    private String origin;
    private String destination;

    public Route(final String origin, final String destination) {
      this.destination = destination;
      this.origin = origin;
    }

    public String getOrigin() {
      return origin;
    }

    public String getDestination() {
      return destination;
    }

    @Override
    public boolean equals(final Object other) {
      if (this == other) return true;
      if (other == null || getClass() != other.getClass()) return false;
      Route __route = (Route) other;
      if (!origin.equals(__route.origin)) return false;
      return destination.equals(__route.destination);
    }

    @Override
    public int hashCode() {
      int hashCode = origin.hashCode();
      hashCode = 31 * hashCode + destination.hashCode();
      return hashCode;
    }
  }
----

Cache keys needs to define a proper `hashCode` and `equals` method.

[IMPORTANT]
.Don't mutate keys
====
For a key instance it is illegal to change its value after it is used for a cache operation.
The cache uses the key instance in its own data structure. When defining your own keys, it is a therefore a
good idea to design them as immutable object.
====

The above isn't special to caching or cache2k, it applies identically when using a Java `HashMap`.

=== Mutating Values

It is illegal to mutate a cached value instance after stored in the cache, unless `storeByReference`
 is enabled. This parameter instructs the cache to keep all cached values inside the heap.

Background: cache2k stores its values in the Java heap by the object reference. This means
mutating a value, will affect the cache contents directly. Future versions of cache2k
will have additional storage options and allow cache entries to be migrated to off heap
storage or persisted. In this case mutating cached values directly will lead to inconsistent
results.

=== Exceptions and Caching

When using read through and a global expiry time (`expireAfterWrite`) is set, exceptions
will be cached and/or suppressed. A cached exception will be rethrown every time the
 key is accessed and after some time, shorter then the expiry time, the loader will
 be called again. A cached exception can be detected by containing the expiry time
 in the exception text, for example:

----
`org.cache2k.integration.CacheLoaderException: expiry=2016-06-04 06:08:14.967, cause: java.lang.NullPointerException`
----

Cached exceptions can be misleading, because you may see 100 exceptions in your log, but only
one was generated from the loader. When a previous value is available a subsequent loader exception
is suppressed an exception for a short time. For more details on this behavior see the *Resilience*
chapter.

=== Don't Panic!

Also those familiar with caching might get confused by the many parameters and operations of cache2k controlling
nuances of caching semantics. Except for the exceptions caching described above everything will work as you will
expect from a cache. There is no need to know every feature in detail. Think of them as a parachute. Usually you
don't need them, but when in trouble, there is one parameter that will save you.

Whenever in doubt: For asking questions please use the _Stackoverflow_ tag `cache2k`. Please describe your scenario
and the problem you try to solve first before asking for specific features of `cache2k` and how they might
help you.
