== Loading / Read Through

When caching reads, using the cache in read through operation is recommended since
 it has several advantages:

 - No boilerplate code as in cache aside
 - Data source becomes configurable
 - Protection against the cache stampede (See https://en.wikipedia.org/wiki/Cache_stampede[Wikipedia: Cache Stampede])
 - Automatic refreshing of expired values (refresh ahead)
 - Build-in exception handling like suppression and retries (see Resilience chapter)

=== Defining a Loader

A loader is defined by implementing the abstract class `CacheLoader`. See the getting
started example.

[source,java]
----
V load(K key) throws Exception;
----

The loader actions may only depend on the input key parameter. In case the load operation
will yield an exception it can be passed to the cache. How exceptions are handled is defined
by the resilience policy.

=== Advanced Loader

For more sophisticated load operations the `AdvancedCacheLoader` is available.

[source,java]
----
 V load(K key, long currentTime, CacheEntry<K,V> currentEntry) throws Exception;
----

The information of the current entry can be used to optimize the data request. For example
if the data is requested by HTTP the header `If-Modified-Since` can be set from
`Entry.getLastModification()`.

=== Prefetching

The cache can be instructed to load one or several values in the background with
the `prefetch()` or `prefetchAll()` operations. This way data retrieval can be
done in parallel and latencies can be reduced.

The number of threads used for prefetching is configured by `loaderThreadCount`.

The operation may have no effect if no loader is defined or if not enough threads
are available.

=== Invalidating

In case the data was updated in the external source, the current cache content
 becomes invalid. To notify the cache and eventually update the cached value
several options exist.

`Cache.remove(key)`::

Invalidating an entry with `Cache.remove()` will cause the entry to be removed from the cache ultimately.
The next time the entry is requested with `Cache.get(key)` the cache will invoke the loader (if defined).
In case the loader yields an exception, this exception will be propagated to the application since there
is no previous value for fallback. `Cache.remove(key)` is useful if the data is outdated and old data is
 not allowed to be delivered. Priority is on data consistency.

`Cache.expireAt(key, Expiry.NOW)`::

The entry is expired immediately. If refresh ahead is enabled the loader will be invoked
in the background. Subsequent calls to `Cache.get` will block until the loading is completed
and return the new value. The operation will have no effect, if there is no cached entry
associated with the key. The value is still available in the cache as fallback if a loader exception occurs.
This variant is the better choice if outdated values are allowed to be visible in the event of
a temporary failure. An inconsistency is only allowed when a temporary failure occurs.

`Cache.expireAt(key, Expiry.REFRESH)`::

When invalidating an entry via `Cache.expireAt(key, Expiry.REFRESH)` the loader
gets invoked instantly if refresh ahead is enabled. If the loader is invoked, the current value
will stay visible until the updated value is available. If the loader cannot be invoked, the entry is
expired. The operation will have no effect, if there is no cached entry associated with the key. The value
is still available in the cache as fallback if a loader exception occurs. This variant is the better
choice if outdated values are allowed to be visible and the cache should continuously serve data.
Priority is on availability.

=== Refresh Ahead

Refresh ahead (or background refresh) can be enabled via `refreshAhead` flag.

The main purpose of refresh ahead is to ensure that the cache contains fresh data
and that an application never is delayed when data expires and needs to be loaded again.
This leads to several compromises: Expired values will be visible until the new
data is available from the load operation, slightly more requests to the loader,
slightly more memory usage.

After the expiry time of a value is reached, the loader is invoked to fetch a fresh value.
The old value will be returned by the cache, although it is expired, and will be replaced
by the new value, once the loader is finished. In the case there are not enough loader
threads available, the value will expire immediately and the next {@code get()} request
will trigger the load. Once refreshed, the entry is in a trail period. If it is not accessed
until the next expiry, no refresh will be done and the entry expires regularly.

Once refreshed, the entry is in a trail period. If it is not accessed until the next
expiry, no refresh will be done and the entry expires regularly. This means that the
time an entry stays within the trail period is determined by the configured expiry time
or the the {@code ExpiryPolicy}. In case an entry is not accessed any more it needs to
reach the expiry time twice before removed from the cache.

The number of threads used for refreshing is configured by `loaderThreadCount`.

NOTE: Refresh ahead only works together with the methods invoking the loader, for example
`get()` and `getAll()`. After a refresh an entry will not be visible with
`containsKey` or `peek`. The first call to `get()` (or `load`) for a refreshed
item will make it appear in the cache again.

The setting `sharpTimeout` conflicts with the idea of refresh ahead. When using
refresh ahead and sharp timeout in combination, the value will expire at the specified
time and the background refresh is initiated. When the application requests the value
between the expiry and before the new value is loaded, it blocks until the new value
is available. Avoid using sharp timeout with refresh ahead. Sharp timeout can also applied
on a per entry basis only when needed.

NOTE: More options to control refreshing and the trail period are added in the next releases.

NOTE: The effects on the listener and statistics when refreshing may change in the future.
