== Refresh Ahead

With refresh ahead (or background refresh), in a read through configuration,
expired values will be refreshed automatically by the cache. This eliminates
that a cache access will cause a delay, when an entry expired before.

=== Setup

Refresh ahead (or background refresh) can be enabled via `refreshAhead` switch.

The number of threads used for refreshing is configured by `loaderThreadCount`.

=== Semantics

The main purpose of refresh ahead is to ensure that the cache contains fresh data
and that an application never is delayed when data expires and needs to be loaded again.
This leads to several compromises: Expired values will be visible until the new
data is available from the load operation, slightly more requests to the loader,
slightly more memory usage.

After the expiry time of a value is reached, the loader is invoked to fetch a fresh value.
The old value will be returned by the cache, although it is expired, and will be replaced
by the new value, once the loader is finished. In the case there are not enough loader
threads available, the value will expire immediately and the next {@code get()} request
will trigger the load. Once refreshed, the entry is in a trail period. If it is not accessed
until the next expiry, no refresh will be done and the entry expires regularly.

Once refreshed, the entry is in a trail period. If it is not accessed until the next
expiry, no refresh will be done and the entry expires regularly. This means that the
time an entry stays within the trail period is determined by the configured expiry time
or the the {@code ExpiryPolicy}. In case an entry is not accessed any more it needs to
reach the expiry time twice before removed from the cache.

TODO: A diagram could help here.

NOTE: Refresh ahead only works together with the methods invoking the loader, for example
`get()` and `getAll()`. After a refresh an entry will not be visible with
`containsKey` or `peek`. The first call to `get()` (or `load`) for a refreshed
item will make it appear in the cache again.

=== Sharp Timeout vs. Refresh Ahead

The setting `sharpTimeout` conflicts with the idea of refresh ahead. When using
refresh ahead and sharp timeout in combination, the value will expire at the specified
time and the background refresh is initiated. When the application requests the value
between the expiry and before the new value is loaded, it blocks until the new value
is available. Avoid using sharp timeout with refresh ahead. Sharp timeout can also applied
on a per entry basis only when needed.

[NOTE]
Combining sharp expiry, lagging expiry and refresh ahead, leads to an operation mode that
cannot guarantee the sharp expiry contract if load operations take too long.
A load needs to take less time then the normal expiry interval.

=== Rationale: No separate refresh timing parameter?

Caches supporting refresh ahead typically have separate configuration parameters for its timing.
In cache2k, refreshing is done when the value would expire, which is controlled by the expiry policy
and `expireAfterWrite` parameter. Why? It should be possible to enable refresh with a single
switch and the cache is doing something useful.

Refreshing and expiring are two sides of the same coin: When expired, we need to refresh.

=== Future Outlook

More options to control refreshing and the trail period are added in the next releases.

The effects on the event listeners and statistics when refreshing may change in the future.
