== About

cache2k is a compact in process cache implementation that has the following main design goals:

Performance:: To achieve high performance cache2k is designed fundamentally different from ground up
  is leveraging an eviction algorithm that allows concurrent read access without locking overhead.
Ease of use:: Well documented API, provide additional features that do not need to much complex configuration
Compact and modular:: Small core size, optional extensions

=== Features

List of current features:

 - The fastest cache (compared to other caches available to us), see http:/benchmarks[the benchmarks]
 - Java 6 and Android compatible
 - Leverages Java 8 to increase performance, when available
 - Portable Java code, no use of `sun.misc.Unsafe`
 - Resilience: Smart exception handling
 - Null value support
 - Expiry: duration or point in time
 - Variable expiry per entry
 - CacheLoader with blocking read through
 - AdvancedLoader for smart requests (e.g. if-modified-since)
 - CacheWriter
 - Events
 - Refresh ahead
 - Efficient statistics
 - JMX support
 - Separate, well defined API
 - Single JAR file for deployment
 - JCache support

=== Versioning

A semantic versioning with Tick-Tock scheme is used. Development versions are marked
by an odd minor version number. Examples:

1.0:: Major version, adds and removes features, incompatible changes to the previous version
1.1.0-BETA:: Odd minor version, development version, possibly unstable API and untested new features
1.2.0:: Even minor version, stable release, new features and compatible to the previous version.
     Not be strictly binary compatible to the previous stable release. Interfaces not meant for
     extension may get new methods.
1.0.1:: Service release. Adds enhancements or fixes bugs. Strictly compatible to the stable release.

Rationale: OSGi doesn't allow alphanumeric qualifiers, so every semantic information is
in the numbers.

=== How to read the documentation

The documentation is intended as a overview guide through the functionality of cache2k and will help
you to discover every important feature. At some points rationale or background
information is given. It is not complete. You will find additional information in the API JavaDoc,
in examples, and in the test cases.
