= JCache

cache2k fully supports the JCache standard and passes 100% of the TCK.

== Using the cache2k with JCache

=== Maven Dependencies

Additionally to the normal cache2k dependencies the following dependencies need to be added:

````
    <dependency>
      <groupId>org.cache2k</groupId>
      <artifactId>cache2k-jcache</artifactId>
      <version>0.26-BETA</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>javax.cache</groupId>
      <artifactId>cache-api</artifactId>
      <version>1.0.0</version>
    </dependency>
    <dependency>
      <groupId>org.cache2k</groupId>
      <artifactId>cache2k-jcache-api</artifactId>
      <version>0.26-BETA</version>
      <scope>compile</scope>
    </dependency>
````

JCache 1.0 is not released with and OSI compatible Open Source license. When using JCache, please
download and review the JCache licensing terms.

=== Getting Started with JCache

Since cache2k is fully JCache compatible, any available JCache introduction can be used for the
first steps. The following online sources are recommended:

=== Configuration

== Implementation Details

=== Expiry Policy



JSR107 does require that the method `ExpiryPolicy.

=== Store by Value

In the standard store by value operation mode, keys and values are copied by the cache whenever
passed in or out. Classes for keys and value must be serializable.

=== Loader exceptions

cache2k is able to cache or suppress exceptions, depending on the situation and the configuration.

If an exception is cached, the following behavior can be expected:

  * Accessing the value of the entry, will trigger an exception
  * `Cache.containsKey()` will be true for the respective key
  * `Cache.iterator()` will skip entries that contain exceptions

=== Listeners

Asynchronous events are delivered in a way to achieve highest possible parallelism while retaining the event
order on a single key. Synchronous events are delivered sequentially.

=== Entry processor

Calling other methods on the cache from inside an entry processor execution (reentrant operation), is not supported.
The entry processor should have no external side effects. To enable asynchronous operations, the execution
may be interrupted by a `RestartException` and restarted.

=== Performance

Using the JCache API does not deliver the same performance as when the native cache2k API is used.
Some design choices in JCache lead to a overhead, for example:

 - Event listeners are attachable at runtime
 - Expiry policy needs to be called for every access
 - Store-by-value semantics require keys and values to be copied
