= Loading / Read Through

== Refresh Ahead

Refresh ahead (or background refresh) can be enabled via `refreshAhead` flag.

The main purpose of refresh ahead is to ensure that the cache contains fresh data
and that an application never is delayed when data expires and needs to be loaded again.
This leads to several compromises: Expired values will be visible until the new
data is available from the load operation, slightly more requests to the loader,
slightly more memory usage.

After the expiry time of a value is reached, the loader is invoked to fetch a fresh value.
The old value will be returned by the cache, although it is expired, and will be replaced
by the new value, once the loader is finished. In the case there are not enough loader
threads available, the value will expire immediately and the next {@code get()} request
will trigger the load. Once refreshed, the entry is in a trail period. If it is not accessed
until the next expiry, no refresh will be done and the entry expires regularly.

Once refreshed, the entry is in a trail period. If it is not accessed until the next
expiry, no refresh will be done and the entry expires regularly. This means that the
time an entry stays within the trail period is determined by the configured expiry time
or the the {@code ExpiryPolicy}. In case an entry is not accessed any more it needs to
reach the expiry time twice before removed from the cache.

The number of threads used for refreshing are configured via `loaderThreadCount`.

NOTE: Refresh ahead only works together with the methods invoking the loader, for example
`get()` and `getAll()`. After a refresh an entry will not be visible with
`containsKey` or `peek`. The first call to `get()` (or `load`) for a refreshed
item will make it appear in the cache again.

The setting `sharpTimeout` conflicts with the idea of refresh ahead. When using
refresh ahead and sharp timeout in combination, the value will expire at the specified
time and the background refresh is initiated. When the application requests the value
between the expiry and before the new value is loaded, it blocks until the new value
is available. Avoid using sharp timeout with refresh ahead. Sharp timeout can also applied
on a per entry basis only when needed.

NOTE: The current semantic of refresh ahead can be useful in many scenarios, but not for all.
More flexibility and configuration options are needed. We plan to look into this in upcoming
releases.

NOTE: Some special cases of the refresh ahead semantics are not yet exactly defined.
 The currently observable effects on the listener and statistics may change in the future.
