= Null Values

While a `HashMap` supports a `null` key and `null` values most cache implementations and the JCache standard
 do not. By default, cache2k does not permit `null` values, but storing null values can be allowed
 with a configuration parameter.

== The Pros and Cons of Nulls

A good writeup of the topic can be found at
https://github.com/google/guava/wiki/UsingAndAvoidingNullExplained[Using and Avoiding Null Explained].
The bottom line is, that for a map it is always better to do not store a mapping if the value
is null instead of storing a mapping to a null value. For a cache it is a different story, since the
absence of a mapping can mean two things: The data was not requested from the source yet, or,
there is no data.

Storing a `null` value in a cache can make sense, when the data source is regularly producing a `null`.
A use case is the request of a database entry by primary key, for example via JPA's
`EntityManager.find()` which returns an object if it is available in the database or `null` if it
is not. There may be applications that regularly test for non existing entries. Then, caching
that an entry is not existing may be equally important to cache an existing entry.

Being able to store a `null` value is no essential cache feature, since it is always possible
to store a wrapper object in the cache. However, with the `null` support in cache2k, it is
possible to store nulls with no additional overhead.

== Default Behavior

By default, every attempt to store a null in the cache will yield a `NullPointerException`.

In case `peek()` returns null, this means there is no associated entry to this
key in the cache. The same holds for `get()` if no loader is defined. For one point
in time and one key there is the following invariant `cache.contains(key) == (cache.peek(key) != null)`.

== How to Enable Null Values

Storing of null values can be enabled by `permitNullValues(true)`. Example:

[source,java]
----
    Cache<Integer, Person> cache =
      new Cache2kBuilder<Integer, Person>(){}
        .name("persons")
        .entryCapacity(10000)
        .expireAfterWrite(5, TimeUnit.MINUTES)
        .permitNullValues(true)
        .build();
----

== How to Operate with Null Values

As soon as null values are legal additional care must be taken when operating with the cache.
The typical cache aside pattern becomes invalid:

[source,java]
----
    Cache<Integer, Person> c = ...
    Person lookupPerson(int id) {
      Person p = cache.peek(id);
      if (p == null) {
        p = retrievePerson(id);
        cache.put(id, p);
      }
      return p;
    }
----

In case `retrievePerson` returns null for a non existing person, it will get called again the next
time the same person is requested. To check whether a mapping is existing `containsKey`. However,
 using `containsKey()` and `get()` sequentially is faulty. To check for the existence of a cache
  entry and return its value the method `peekEntry` (or `getEntry` with loader) can be used.
  The fixed version is:

[source,java]
----
    Cache<Integer, Person> c = ...
    Person lookupPerson(int id) {
      CacheEntry<Person> e = cache.peekEntry(id);
      if (e != null) {
        return e.getValue();
      }
      p = retrievePerson(id);
      cache.put(id, p);
      return p;
    }
----

The cache aside pattern serves as a good example here, but is generally not recommended. Better
use read through and define a loader.

== Loader and Null Values

If a loader is defined a call of `get()` will either return a non-null value or yield an exception.
If the loader returns null, a `NullPointerException` is generated and wrapped and propagated via
a `CacheLoaderException`.

This behavior is different from JSR107/JCache which defines that an entry is removed, if the loader
returns null. Within cache2k the default behavior is to fail fast. This intentional, see the
rationale.

In case the loader returns `null` and this should not lead to an exception the following options exist:

- Always return a non-null object and include a predicate for the null case.
  Sometimes it is desirable to transport more information anyway. E.g. when requesting
  a resource via HTTP null can mean "resource not available", however it may be
  better to pass on the cause from the HTTP status code.
- Enable null value support
- Remove entries from the cache when the loader returns null (as in JCache)

The expiry policy can be used to remove entries from the cache when the loader returns null:

[source,java]
----
    ...
    builder.expiryPolicy(new ExpiryPolicy<Integer, Person>() {
      @Override
      public long calculateExpiryTime(K key, V value, long loadTime, CacheEntry<Integer, Person> oldEntry) {
        if (value == null) {
          return NO_CACHE;
        }
        return ETERNAL;
      }
    })
    ...
----

This works, since the cache checks the null value only after the expiry policy has run and
 had decided to store the value.

== Performance

Storing nulls has no additional memory or CPU overhead.

== Rationale

=== Why support nulls?

Supporting nulls needs a more careful design inside the cache. When
this is done, it basically comes for free and makes the cache very effective for use cases
where nulls are common, e.g. database persistence layers.

=== Why is rejecting null values the default?

We were using cache2k for 16 years, with the capability
 to store nulls by default. For the 1.0 version we changed this behavior and don't allow nulls.
 Here is why:

- Most caches do not support null values. Allowing null by default may lead to unexpected behavior.
- Use cases with null are rare.
- Returning ore storing a null may be a mistake most of the time, so better fail fast.
- In case a null is allowed it is better to specify this explicitly to make the different
  behavior more obvious

=== Why rejecting nulls from the loader?

If the loader returns null, a `NullPointerException` is generated and propagated via
the `CacheLoaderException`. This behavior is different from JSR107/JCache which defines that an entry
is removed, if the loader returns null.

The JCache behavior is consistent, since a `get()` in JCache returns null only in the case that
no entry is present. The JCache behavior is also useful, since nulls from the loader pass through
transparently. But as soon as nulls are passed through regularly, the cache will become void.
This will be unnoticed during development but will lead to trouble in production and is a DOS attack
vector as well.

In cache2k there a different options when `null` comes into play. A consistent fail fast
by default will lead to an explicit choice for the best option.
