= Getting started

== Obtaining cache2k

The latest cache2k version is available on maven central. The recommended way to include ir
in your project is to add the following dependencies:

[source,xml,subs="attributes+"]
----
    <properties>
      <cache2k.version>{project.version}</cache2k.version>
    </properties>

    <dependencies>
        <dependency>
          <groupId>org.cache2k</groupId>
          <artifactId>cache2k-api</artifactId>
          <version>${cache2k.version}</version>
          <scope>compile</scope>
        </dependency>
        <dependency>
          <groupId>org.cache2k</groupId>
          <artifactId>cache2k-all</artifactId>
          <version>${cache2k.version}</version>
          <scope>runtime</scope>
        </dependency>
     </dependencies>
----

This will add the single `cache2k-all` JAR file to your application deliverable. For compiling and development
 the `cache2k-api` is included which contains API classes meant for cache clients and no implementation classes.
 Everything inside the API is kept stable and is well documented.

The above requires at least a `Java SE 6` compatible runtime. For inclusion with Android, see the Android chapter.

== Building a Cache


== Cache Aside


== Read Through


== Surprising Behavior

When using read through and a global expiry time (`expireAfterWrite`) is set, exceptions
will be cached and/or suppressed. A cached exception will be rethrown every time the
 key is accessed and after some time, shorter then the expiry time, the loader will
 be called again. A cached exception can be detected by containing the expiry time
 in the exception text, for example:

----
`org.cache2k.integration.CacheLoaderException: expiry=2016-06-04 06:08:14.967, cause: java.lang.NullPointerException`
----

Cached exceptions can be misleading, because you may see 100 exceptions in your log, but only
one was generated from the loader. When a previous value is available a subsequent loader exception
is suppressed an exception for a short time. For more details on this behavior see the *Resilience*
chapter.

== Don't Panic!

Also those familiar with caching might get confused by the many parameters and operations of cache2k controlling
nuances of caching semantics. Except for the exceptions caching described above everything will work as you will
expect from a cache. There is no need to know every feature in detail. Think of them as a parachute. Usually you
don't need them, but when in trouble, there is one parameter that will save you.

Whenever in doubt: For asking questions please use the _Stackoverflow_ tag `cache2k`. Please describe your scenario
and the problem you try to solve first before asking for specific features of `cache2k` and how they might
help you.
