= Resilience

In a read through configuration the cache can tolerate temporary loader failures.
The write trough does not provide resilience capabilities at the moment, which means
 a writer exception will always propagated to the cache client.

== Default behavior

The default behavior depends on the general expiry (`expiryAfterWrite`) setting of the cache.
If no expiry is specified, all exceptions will be propagated to the client. The loader will be
called immediately again, if the key is requested again.

With specifying the expiry, the cache also enables the resilience features.
If a load yields an exception and there is data in the cache: The exception is not propagated
to the client, and the cache answers requests with the current cache content. Subsequent
load attempts that yield an exception, will also be _suppressed_, if the time span to the
first exception is below the expiry duration setting. If the loader produces
subsequent exceptions that is longer then the configured expiry,
the exception will be _propagated_. This time span can be modified (`resilienceDuration`).

After an exception the cache will retry to load the value again after 5% of the expiry
duration is passed. The load attempt is triggered when the client accesses the value
again, or the cache is doing this by itself if `refreshAhead` is enabled.

To keep the load in limits in the event of failure, the duration between each retry
increases according to an _exponential backoff_ pattern by the factor of 1.5.
Each duration is further randomized between one half and the full value.
For example, an `expireAfterWrite` set to 200 seconds will lead to an initial retry
time of 10 seconds. If exceptions persist the retry time will develop as follows:

.Retry intervals with exponential backoff starting at 10 seconds
[width="70",options="header"]
,===
base duration,randomized duration range
10 seconds,5 - 10 seconds
15 seconds,7.5 - 115 seconds
22.5 seconds,11.25 - 22.5 seconds
33.75 seconds,16.875 - 33.75 seconds
,===

When reaching the configured expiry the cache will retry at this time interval and
not increase further. The start retry interval and the maximum retry interval can
be specified by `retryInterval` and `maxRetryInterval`.

If an exception cannot be suppressed, it is propagated to the client immediately.
The retry attempts follow the same pattern as above.

When propagated, a loader exception is wrapped and rethrown as `CacheLoaderException`.
A loader exception is potentially rethrown multiple times, if the retry time is not
yet reached. In this situation a rethrown exception contains the text `until=<timestamp>`.
This behavior can be customized by the `ExceptionPropagator`.

== Configuration options

To customize the behavior the following

suppressExceptions:: Default is true. If set to false, do not suppress exceptions.
expireAfterWrite:: Time duration after insert or updated an cache entry expires
resilienceDuration:: Time span the cache will suppress loader exceptions if a value is available from
                     a previous load. Defaults to `expiredAfterWrite`
mayRetryInterval:: The maximum time interval after a retry attempt is made. Defaults to `resilienceDuration`
retryInterval:: Initial time interval after a retry attempt is made. Defaults to 10% of `mayRetryInterval`, or a minimum of 2 seconds.
resiliencePolicy:: Sets a custom resilience policy to control the cache behavior in the presence of exceptions
exceptionPropagator:: Sets a custom behavior for exception propagation

== Examples

=== No expiry

Values do not expire, exceptions are not suppressed and an immediately
retry is done.

[source,java]
----
    Cache<Integer, Integer> c = new Cache2kBuilder<>() {}
      .eternal(true)
      /* ... set loader ... */
      .build();
----

=== Expire after 10 minutes

Values expire after 10 minutes. Exceptions are suppressed for 10 minutes
as well, if possible. A retry attempt is made until 1 minute. If the cache
continuously receives exceptions for a key, the retry intervals are exponentially
increased up to 10 minutes.

[source,java]
----
    Cache<Integer, Integer> c = new Cache2kBuilder<>() {}
      .expireAfterWrite(10, TimeUnit.MINUTES)
      /* ... set loader ... */
      .build();
----

=== Reduced suppression time

Expire entries after 10 minutes. If an exceptions happens we do not want
 the cache to continue to service the previous (and expired) value for too long. In this scenario
 it is preferred to propagate an exception rather than serving a potentially outdated value.
 On the other side, there may be temporary outages of the network for a maximum of 30 seconds
 we like to cover for.

[source,java]
----
    Cache<Integer, Integer> c = new Cache2kBuilder<Integer, Integer>() {}
      .expireAfterWrite(10, TimeUnit.MINUTES)
      .resilienceDuration(30, TimeUnit.SECONDS)
      /* ... set loader ... */
      .build();
----

=== Cached exceptions

No suppression, because values never expire. The only way that a reload can be triggered
is with a reload operation. In this case we do not want suppression, unless
specified explicitly. The loader is not totally reliable, or a smart developer
uses an exception to signal additional information. If exceptions occur, the cache
should not be ineffective and keep exceptions and defer the next retry for 10 seconds.
For requests between the retry interval, the cache will rethrow the previous exception.
The retry interval does not increase, since a maximum timer interval is not specified.

[source,java]
----
   Cache<Integer, Integer> c = new Cache2kBuilder<Integer, Integer>() {}
      .eternal(true)
      .retryInterval(10, TimeUnit.SECONDS)
      /* ... set loader ... */
      .build();
----

== Custom resilience policy

By registering a custom implementation of the resilience policy it is possible to
implement a special behavior that is used to determine the durations an exception should be
suppressed or cached. Use the existing implementation as an example and starting point.

== Debugging

The cache has no support for logging exceptions. If this is needed, it can be achieved
by an adaptor of the `CacheLoader`.


exceptions counter


